services:
  - type: web
    name: reposture-frontend
    env: static
    staticPublishPath: frontend

  - type: web
    name: reposture-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend/app.py"
    envVars:
      - key: FLASK_ENV
        value: production